import type { MeetupDTO, UserDTO } from './types/meetups.types.ts'

export const strings = ['one', 'two', 'three', 'four', 'five']

export const users: UserDTO[] = [
  {
    id: 1,
    fullname: 'Alice',
    email: 'alice@course-vue.javascript.ru',
    avatar: 'https://www.gravatar.com/avatar/01587446428e5fef0ac9289c76c8e228c39fbd5b19228d0ca2161cb4964b835b',
  },
  {
    id: 2,
    fullname: 'Bob',
    email: 'bob@course-vue.javascript.ru',
    avatar: 'https://www.gravatar.com/avatar/c916c0f249074f77e129c584c4775ddf2c23c5ab7b2c0613460b8ba8c5fd6d49',
  },
  {
    id: 3,
    fullname: 'John',
    email: 'john@course-vue.javascript.ru',
    avatar: 'https://www.gravatar.com/avatar/c8383afd5e464f504ac6561febf32b09770106d81f37d20f35e0f5fb11887bf6',
  },
  {
    id: 4,
    fullname: 'Jane',
    email: 'jane@course-vue.javascript.ru',
    avatar: 'https://www.gravatar.com/avatar/323fcb6754e15d50773a31239c6ed9bbef5688cb3e091a4c9f35ad23adbe58fe',
  },
]

export const meetups: MeetupDTO[] = [
  {
    id: 1,
    title: 'MSK VUE.JS MEETUP #1',
    description:
      'С каждым днем Vue.js становится популярней, все больше разработчиков и компаний делают ставку на данную технологию — 18 июля при поддержке компании Voximplant пройдет митап сообщества MSK VUE.JS, посвященный фреймворку. Спикеры поделятся опытом разработки, участники сообщества обсудят перспективы развития Vue.js.\n\nhttps://voximplant.timepad.ru/event/986750/',
    imageId: 1,
    image: 'https://course-vue.javascript.ru/api/images/1.jpeg',
    date: 1720396800000,
    dateIso: '2024-07-08',
    organizer: 'Игорь Ш.',
    place: 'Москва, офис Voximplant (ул. Мытная 66)',
    organizing: false,
    attending: true,
    agenda: [
      {
        id: 1,
        startsAt: '18:30',
        endsAt: '19:00',
        type: 'registration',
        title: null,
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 2,
        startsAt: '19:00',
        endsAt: '19:45',
        type: 'talk',
        title: 'Vue.js 3 — все что ждет нас в будущем',
        description:
          'Скоро нас ждет Vue.js 3. Теперь наш любимый фреймворк станет лучше, быстрее, моднее. Давайте поговорим, что нового нас ждет, что мы получим и что потеряем в результате обновления. Рассмотрим технологии, которыми обогатится Vue.js и которые сделают его, на мой взгляд, самым быстрым и простым фреймворком на рынке.',
        speaker: 'Игорь Шеко — Lead Developer, Voximplant',
        language: 'RU',
      },
      {
        id: 3,
        startsAt: '19:45',
        endsAt: '20:15',
        type: 'coffee',
        title: null,
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 4,
        startsAt: '20:15',
        endsAt: '21:00',
        type: 'talk',
        title: 'Опыт использования Vue.js в «Едадиле»',
        description:
          '— Долгая жизнь с Vue: промышленное использования начиная с версии 0.x.\n— Vue внутри webview нативного приложения: подводные камни.\n— Не «стандартный подход» к организации кода и сборке.\n— Авто-оптимизация приложения Vue.\n— Настоящая изоморфность: Vue и другой рантайм.',
        speaker: 'Андрей Кобец — Руководитель отдела разработки фронтенда «Едадила», Яндекс',
        language: 'RU',
      },
      {
        id: 5,
        startsAt: '21:00',
        endsAt: '21:45',
        type: 'talk',
        title: 'Прогрессивные приложения на прогрессивном фреймворке',
        description:
          'PWA (progressive web app, прогрессивное веб-приложение) — один из главных трендов в вебе последние 2 года. Наверняка, вы не раз о нем слышали и даже не раз делали. Или, как я, давно хотели попробовать, но на рабочих проектах в нем не было необходимости. Этот доклад для неслышавших или слышавших, но не пробовавших. Расскажу, что такое PWA, какие технологии подразумевает, в каких браузерах они работают, как интегрировать их во vue-приложение, чем тестировать и какие удобные готовые решения есть можно использовать.',
        speaker: 'Ольга Лесникова — Senior Developer, Voximplant',
        language: 'RU',
      },
      {
        id: 6,
        startsAt: '22:00',
        endsAt: '22:00',
        type: 'closing',
        title: null,
        description: null,
        speaker: null,
        language: null,
      },
    ],
  },
  {
    id: 2,
    title: 'Vue.js Moscow Meetup #1',
    description:
      'Ссылка на трансляцию: https://www.youtube.com/watch?v=h9NQs0SEVoA\n\nДрузья привет! Рады сообщить о первом московском митапе, посвященном исключительно фреймоврку Vue.js.\n\nНаша встреча пройдет 22 марта 2018 под покровительством компании Acronis в технопарке - Физтехпарк (г.Москва, Долгопрудненское шоссе, д.3)\nПриглашаются все заинтересованные разработчики от начинающих до опытных.\nФизтехпарк находится за МКАД, но не беспокойтесь, будет организован трансфер от станции метро Алтуфьево и после мероприятия обратно.\nДля желающим приехать на собственном транспорте, проблем с парковкой не будет. Для тех кто все же не сможет до нас добраться, будет организована трансляция выступлений.\n\nhttps://www.meetup.com/ru-RU/vue-js-moscow/events/248462774/',
    imageId: 2,
    image: 'https://course-vue.javascript.ru/api/images/2.jpeg',
    date: 1719014400000,
    dateIso: '2024-06-22',
    organizer: 'Eugeny F.',
    place: 'Москва, Физтехпарк, офис Acronis',
    organizing: false,
    attending: true,
    agenda: [
      {
        id: 28,
        startsAt: '18:30',
        endsAt: '19:00',
        type: 'registration',
        title: 'Сбор и трансфер',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 29,
        startsAt: '19:00',
        endsAt: '19:30',
        type: 'talk',
        title: 'Практика и методы работы со сложными формами во Vue.js',
        description:
          'В докладе на примере от простого к сложному, рассмотрим основные методы и архитектурные подходы работы с редактируемыми пользовательскими данными в современных frontend приложениях.',
        speaker: 'Александр Башкирцев (Software developer, Acronis)',
        language: 'RU',
      },
      {
        id: 30,
        startsAt: '19:30',
        endsAt: '20:00',
        type: 'talk',
        title: 'Внедряем Vue.js в готовый проект, безболезненное избавление от jQuery.',
        description:
          'Что если нам достался в наследство сайт состоящий из неструктурированной, неподдерживаемой лапши из html-css-jquery.... Давайте не будем расстраиваться, а засучим рукава, возьмем в руки vue.js и заставим наше наследство сиять по новому!',
        speaker: 'Alexander Mayorov (CTO, NewHR)',
        language: 'RU',
      },
      {
        id: 31,
        startsAt: '20:00',
        endsAt: '20:10',
        type: 'coffee',
        title: 'Перерыв на кофе и обсуждения',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 32,
        startsAt: '20:10',
        endsAt: '20:40',
        type: 'talk',
        title: 'Простое и понятное управление состоянием во vue.js',
        description:
          'Веб-фреймворки хорошо помогают создавать сложные системы с большим жизненным циклом. Но при решении простых задач современные идеи начинают показывать себя с другой стороны. Разработка компонентов даже с простой бизнес-логикой забирает на себя слишком много времени. Vue хорошо показывает себя в упрощении разработки. Но есть еще места, в которых бывает многовато кода на единицу бизнес-логики. В докладе я расскажу и покажу на примерах как сделать код приложения на Vue еще проще, не потеряв в надежности и выразительности.',
        speaker: 'Александр Сафт (Senior Frontend Developer, Смотрешка)',
        language: 'RU',
      },
      {
        id: 33,
        startsAt: '20:40',
        endsAt: '21:10',
        type: 'talk',
        title: 'Опыт использования Nuxt.js',
        description:
          'Фреймворк Nuxt.js позволяет очень быстро собирать на Vue.js статические сайты. Получающиеся пререндеренные HTML страницы грузятся очень быстро, затем загружают JavaScript код и оживают в ваше приложение. Мы в Voximplant используем Nuxt для внутренних проектов, документации, одностраничных сайтов. В докладе я кратко расскажу про сам фреймворк, его возможности, ограничения, сильные и слабые стороны - и, конечно же, нашу практику его использования',
        speaker: 'Григорий Петров (технический евангелист Voximplant)',
        language: 'RU',
      },
      {
        id: 34,
        startsAt: '21:10',
        endsAt: '23:00',
        type: 'afterparty',
        title: 'Жгучее afterpaty, итальянская пицца, вкусные напитки и продуктивный нетворкинг',
        description: null,
        speaker: null,
        language: null,
      },
    ],
  },
  {
    id: 3,
    title: 'Vue.js Moscow Meetup #2 - Mail.ru',
    description:
      '!!! Внимание !!!\nРегистрация строго по ссылке:\nhttps://corp.mail.ru/ru/press/events/481/ (Регистрация закрыта)\nВы не сможете попасть на мероприятия, не пройдя регистрацию по ссылке выше.\n\nДрузья привет! Открываем регистрацию на вторую встречу JavaScript/Vue.js разработчиков и всех интересующихся.\nДля тех кто все же не сможет до нас добраться, будет организована трансляция выступлений.\n\nhttps://www.meetup.com/ru-RU/vue-js-moscow/events/251880636/\nСсылка на онлайн трансляцию: https://www.youtube.com/watch?v=SiPKxngecQ0',
    imageId: 3,
    image: 'https://course-vue.javascript.ru/api/images/3.jpeg',
    date: 1720137600000,
    dateIso: '2024-07-05',
    organizer: 'Eugeny F.',
    place: 'Москва, Офис компании Mail.Ru Group',
    organizing: false,
    attending: false,
    agenda: [
      {
        id: 14,
        startsAt: '18:30',
        endsAt: '19:00',
        type: 'registration',
        title: 'Сбор и регистрация',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 15,
        startsAt: '19:00',
        endsAt: '19:30',
        type: 'talk',
        title:
          'Почему Vue.js одинаково хорош для внедрения в legacy код и для построения архитектуры большого приложения с нуля.',
        description:
          'На примерах того как мы в Delivery Club:\n- внедряли vue.js в legacy проект 2009 года.\n- писали приложение на стеке vue + vuex + typescript + rxjs с нуля\n- пишем новый проект на vue.js\nрасскажу и покажу «от простого к сложному», каким может быть vue.js в вашем проекте.',
        speaker: 'Никита Крикун, Frontend Developer, Mail.Ru Group (Delivery Club)',
        language: 'RU',
      },
      {
        id: 16,
        startsAt: '19:30',
        endsAt: '20:00',
        type: 'talk',
        title: 'Сложные анимации во Vue.js',
        description:
          'Анимация состояний и переходов во Vue на примере боевого сайта. От стандартных средств до Timeline-анимации переходов между страницами с помощью сторожевых хуков vue-router и Green Sock.',
        speaker:
          'Сергей Корниенко, Frontend teamlead в Beta Digital Production, преподаватель курса по Vue.js в Moscow Coding School',
        language: 'RU',
      },
      {
        id: 17,
        startsAt: '20:00',
        endsAt: '20:10',
        type: 'coffee',
        title: 'Перерыв на кофе и обсуждения',
        description: null,
        speaker: null,
        language: null,
      },
      {
        id: 18,
        startsAt: '20:10',
        endsAt: '20:40',
        type: 'talk',
        title: 'Замечательный PWA',
        description:
          'Настало время, когда можно перестать писать код ради кода. Время, когда не надо держать отдельные отделы разработки для написания одних и тех же приложений под разные платформы. PWA – это решение многих проблем кроссплатформенной разработки доступное здесь и сейчас.',
        speaker: 'Владислав Смирнов, Frontend разработчик, Comindware',
        language: 'RU',
      },
      {
        id: 19,
        startsAt: '20:40',
        endsAt: '21:10',
        type: 'talk',
        title: 'Модульно-микросервисная архитектура на на Vue.js',
        description:
          'Мы в ведомостях любим микросервисы. А ещё мы любим Vue.js. В этом докладе я расскажу про опыт объединения микросервисов и вариант реализации модулей в рамках экосистемы Vue.',
        speaker: 'Антон Федоров, Ведущий фронтенд-разработчик, Ведомости',
        language: 'RU',
      },
      {
        id: 20,
        startsAt: '21:10',
        endsAt: '23:00',
        type: 'closing',
        title: 'Завершение; Cбор на afterparty',
        description: null,
        speaker: null,
        language: null,
      },
    ],
  },
]
